// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login valid and invalid inputs', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login valid and invalid inputs', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1296, height: 688 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("idCard")).click()
    await driver.findElement(By.id("idCard")).sendKeys("3138761616")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("12345678")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("idCard")).click()
    await driver.findElement(By.id("idCard")).sendKeys("318761616")
    await driver.findElement(By.css("button")).click()
  })
})
