// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('registration valid inputs (student)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('registration valid inputs (student)', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 620, height: 462 })
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("nicolas")
    await driver.findElement(By.id("lastName")).click()
    await driver.findElement(By.id("lastName")).sendKeys("s")
    await driver.findElement(By.id("idCard")).click()
    await driver.findElement(By.id("idCard")).sendKeys("123764893")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("111111111")
    await driver.findElement(By.css("button")).click()
  })
})
